[workspace]
default-members = [".", "crates/*"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/juspay/nix-browser"

[workspace.dependencies]
cfg-if = "1"
clap = { version = "4.3", features = ["derive", "env"] }
human-panic = "1.1.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix_rs = { version = "0.2", path = "./crates/nix_rs" }
nix_health = { path = "./crates/nix_health" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.2", features = ["json"] }
bytesize = { version = "1.3.0", features = ["serde"] }
anyhow = { version = "1.0.75" }

[package]
edition = "2021"
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "nix-browser"
version = "0.1.0"
homepage = "https://github.com/juspay/nix-browser"

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cfg-if.workspace = true
clap.workspace = true
console_error_panic_hook = "0.1"
console_log = { version = "1" }
http = { version = "0.2" }
human-panic.workspace = true
regex = "1.9.3"
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio = { version = "1.29", features = ["process"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid = { version = "1.3.0", features = ["serde", "v4", "js"] }
nix_rs.workspace = true
nix_health.workspace = true
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "459f24d5e9ef0e03a3bbd037342c60bbde409dbf" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "459f24d5e9ef0e03a3bbd037342c60bbde409dbf" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "459f24d5e9ef0e03a3bbd037342c60bbde409dbf" }
dioxus-signals = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "459f24d5e9ef0e03a3bbd037342c60bbde409dbf" }
dioxus-std = { version = "0.4.0", features = ["clipboard", "utils"] }

[features]
# TODO: remove this now unnecessary flag
default = ["ssr"]
ssr = ["nix_rs/ssr", "nix_health/ssr"]
