[workspace]
resolver = "2"

members = ["crates/nix-browser"]

[workspace.dependencies]
cfg-if = "1"
clap = "4.3"
human-panic = "1.1.5"
tracing = "0.1"
tracing-subscriber = "0.3"
nix_rs = "0.3.2"
direnv = "0.1.1"
nix_health = "0.3.0"
thiserror = "1.0"
serde = "1.0.197"
serde_json = "1.0"
serde_with = "3.2"
bytesize = "1.3.0"
anyhow = "1.0.75"
console_error_panic_hook = "0.1"
console_log = "1"
http = "0.2"
regex = "1.9.3"
tokio = "1.33.0"
uuid = "1.3.0"
fermi = "0.4.3"
