[workspace]
resolver = "2"

members = ["crates/omnix", "crates/omnix-cli", "crates/omnix-gui"]

[workspace.dependencies]
anyhow = "1.0.75"
bytesize = { version = "1.3.0", features = ["serde"] }
cfg-if = "1"
clap = { version = "4.3", features = ["derive", "env"] }
console_error_panic_hook = "0.1"
console_log = "1"
direnv = "0.1.1"
fermi = "0.4.3"
http = "0.2"
human-panic = "1.1.5"
nix_health = "0.3.0"
nix_rs = "0.3.2"
omnix = { path = "./crates/omnix" }
regex = "1.9.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.2", features = ["json"] }
thiserror = "1.0"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.3.0", features = ["serde", "v4", "js"] }
