[package]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/juspay/nix-browser"
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "nix-browser"
version = "0.1.0"
homepage = "https://github.com/juspay/nix-browser"
build = "build.rs"

[dependencies]
cfg-if = "1"
clap = { version = "4.3", features = ["derive", "env"] }
human-panic = "1.1.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix_rs = "0.3.2"
direnv = "0.1.1"
nix_health = "0.3.0"
thiserror = "1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.2", features = ["json"] }
bytesize = { version = "1.3.0", features = ["serde"] }
anyhow = "1.0.75"
console_error_panic_hook = "0.1"
console_log = "1"
http = "0.2"
regex = "1.9.3"
tokio = { version = "1.33.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["serde", "v4", "js"] }
# Using git until Dioxus 0.5 release.
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b19a546c0ac639a5cf9e942fff7729ad30e91a5e" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b19a546c0ac639a5cf9e942fff7729ad30e91a5e" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b19a546c0ac639a5cf9e942fff7729ad30e91a5e" }
dioxus-signals = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "b19a546c0ac639a5cf9e942fff7729ad30e91a5e" }
# TODO: Using https://github.com/DioxusLabs/dioxus-std/pull/17 which was merged, so we must switch back to 0.5 version along with Dioxus upgrade.
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk.git", rev = "809d90440988a55a2db3b816de67e2c219f19865", features = [
    "storage",
] }
fermi = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "c7963a03440d5a050bf229f91665d60a0d108a8a" }

[package.metadata.docs.rs]
all-features = true
