[application]
name = "omnix-gui"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Omnix | 🌍"

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true
# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

[web.resource]
# CSS style file
style = ["tailwind.css"]
# Javascript code file
script = []

[web.resource.dev]
# CSS style file
style = []
# Javascript code file
script = []

# FIXME: Need to `cd assets` before running `dx bundle` due to https://github.com/DioxusLabs/dioxus/issues/1283
[bundle]
name = "Omnix"
identifier = "in.juspay.omnix"
icon = ["images/128x128.png"]  # ["32x32.png", "128x128.png", "128x128@2x.png"]
version = "1.0.0"
# TODO: Must add these files
resources = ["**/tailwind.css", "images/**/*.png"] # , "secrets/public_key.txt"]
copyright = "Copyright (c) Juspay 2023. All rights reserved."
category = "Developer Tool"
short_description = "Graphical user interface for Omnix"
long_description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
"""
osx_frameworks = []
