[package]
edition = "2021"
name = "nix_rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
clap = { version = "4.3", features = ["derive", "env"] }
console_error_panic_hook = "0.1"
console_log = { version = "1" }
http = { version = "0.2", optional = true }
human-panic = "1.1.5"
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
log = "0.4"
regex = "1.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.2", features = ["json"] }
thiserror = "1.0"
tokio = { version = "1.29", features = ["full"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.4", features = ["full"], optional = true }
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-subscriber-wasm.workspace = true
url = { version = "2.4", features = ["serde"] }
uuid = { version = "1.3.0", features = ["serde", "v4", "js"] }

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
    "dep:http",
    "dep:tokio",
    "dep:tower-http",
    "dep:tower",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "leptos/ssr",
]
