[package]
name = "omnix-cli"
version = "0.1.0"
edition = "2021"
default-run = "om"

[[bin]]
name = "om"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
colored = { workspace = true }
flakreate = { workspace = true }
human-panic = { workspace = true }
nix_health = { workspace = true }
nix_rs = { workspace = true }
omnix = { workspace = true }
tabled = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
anyhow = { workspace = true }
