name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [ x86_64-linux, aarch64-darwin ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v14
        with:
          name: om
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: |
          # Prep systems list
          # https://github.com/srid/nixci/issues/83
          mkdir ~/systems
          echo '{ outputs = _: {}; }' > ~/systems/flake.nix
          echo '[ "${{ matrix.system }}" ]' > ~/systems/default.nix

          # Build all flake outputs
          nixci \
            --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} \
            build --systems "path:$HOME/systems"
      # In lieu of https://github.com/srid/nixci/issues/88
      - name: Registry flake check
        run: |
          cd ./crates/flakreate/registry
          nix --accept-flake-config flake check
      - name: CLI Tests
        run: |
          # We disable tests on Nix due to sandboxing issues.
          cd ./crates/omnix-cli
          nix --accept-flake-config develop -c cargo test

      # TODO: Move this to omnix-cli tests?
      # First, build the repos used in the test to cache them locally, so as
      # to avoid GitHub rate limits during the integration test (which
      # doesn't use the token)
      - name: nixci integration test (preparation)
        run: |
          nixci --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" build "github:srid/haskell-multi-nix/c85563721c388629fa9e538a1d97274861bc8321" -- --no-link
          nixci --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" build "github:juspay/services-flake/3d764f19d0a121915447641fe49a9b8d02777ff8" -- --no-link
      - name: nixci integration test
        run: |
          cd ./crates/nixci
          nix --accept-flake-config develop -c cargo test -F integration_test

