name: "CI"
on:
  push:
    branches:
      - main
      - workspace
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [ x86_64-linux, aarch64-darwin ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: nixci --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} build --systems "${{ matrix.system }}"
