name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [ x86_64-linux, aarch64-darwin, x86_64-darwin ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v14
        with:
          name: om
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: |
          # Prep systems list
          # https://github.com/srid/nixci/issues/83
          mkdir ~/systems
          echo '{ outputs = _: {}; }' > ~/systems/flake.nix
          echo '[ "${{ matrix.system }}" ]' > ~/systems/default.nix

          # Build all flake outputs
          nixci \
            --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} \
            build --systems "path:$HOME/systems"
      # In lieu of https://github.com/srid/nixci/issues/88
      - name: Registry flake check
        run: |
          cd ./crates/flakreate/registry
          nix --accept-flake-config flake check
      - name: CLI Tests
        run: |
          # We disable tests on Nix due to sandboxing issues.
          cd ./crates/omnix-cli
          nix --accept-flake-config develop -c cargo test
