name: "CI"
on:
  workflow_run:
    workflows: ["Garnix CI"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix --accept-flake-config build --no-link --print-out-paths .#e2e-playwright-test
      - name: E2E tests
        run: nix --accept-flake-config run .#e2e-playwright-test
