name: "Static binary"
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  check:
    needs: main
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Donwload om static binary
        uses: actions/download-artifact@v4
        with:
          name: om-${{ matrix.system == 'ubuntu-latest' && 'x86_64-linux' || matrix.system == 'macos-latest' && 'aarch64-darwin' || matrix.system }}
      - name: Check nix installation
        run: |
          if which nix; then
            echo "nix is installed, exiting"
            exit 1
          elif test -d /nix; then
            echo "/nix is present, exiting"
            exit 1
          else
            echo "nix is not installed"
          fi
      - name: Run om static binary
        run: |
          chmod +x ./om
          ./om --help
